name: Grunt

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Install dependencies
      run: |
        npm install --save-dev

    - name: Generate documentation
      run: npm run doc
      
    - name: Run Grunt test
      run: npm run test
